version: "3.9"
services:
  web:
    build: ./frontend
    ports:
    - "80:80"
    depends_on:
      - auction-service
  auction-service:
    build: ./backend
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=auction
      - POSTGRES_USER=auction
      - POSTGRES_PASSWORD=auction
